---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Разработать интерфейс магазина по продаже товаров с просмотром, фильтрацией товаров и добавлением их в корзину. Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах.
  - Также магазин — это SPA приложение, которое не перезагружает страницу.
  - Корзина хранится в сессии браузера.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - В интерфейсе должна быть кнопка описание товора.
  - Добавлена кнопка для регулирования кол-во товара в корзине.
  - Кнопка добавления в корзину подсвечена синим цветом.
  - Кнопка удаления товара из корзины подсвечена красным цветом.
